import { prisma } from '../config/database';
import * as fs from 'fs';
import * as path from 'path';
import { sendEmailReport } from './email.service';
import { reportEngine } from './reporting-engine';

// Priority map for deterministic severity sorting
const SEVERITY_WEIGHT: Record<string, number> = {
  critical: 4,
  high: 3,
  medium: 2,
  low: 1
};

/**
 * Get ISO week string, e.g., "2026-W30"
 */
function getISOWeekString(date: Date): string {
  const d = new Date(Date.UTC(date.getFullYear(), date.getMonth(), date.getDate()));
  const dayNum = d.getUTCDay() || 7;
  d.setUTCDate(d.getUTCDate() + 4 - dayNum);
  const yearStart = new Date(Date.UTC(d.getUTCFullYear(),0,1));
  const weekNo = Math.ceil((((d.getTime() - yearStart.getTime()) / 86400000) + 1)/7);
  return `${d.getUTCFullYear()}-W${weekNo.toString().padStart(2, '0')}`;
}

/**
 * Get month string, e.g., "2026-07"
 */
function getMonthString(date: Date): string {
  return `${date.getUTCFullYear()}-${(date.getUTCMonth() + 1).toString().padStart(2, '0')}`;
}
/**
 * Helper to retry a promise-returning function with exponential backoff.
 * Future migration to BullMQ will replace this with built-in queue retries.
 */
async function withRetry<T>(fn: () => Promise<T>, retries = 3, baseDelayMs = 1000): Promise<T> {
  let attempt = 0;
  while (attempt < retries) {
    try {
      return await fn();
    } catch (error) {
      attempt++;
      if (attempt >= retries) throw error;
      const delay = baseDelayMs * Math.pow(2, attempt - 1);
      console.warn(`[RETRY] Attempt ${attempt} failed, retrying in ${delay}ms...`);
      await new Promise(res => setTimeout(res, delay));
    }
  }
  throw new Error('Unreachable');
}

export const reportService = {
  generatePdfReport: async (assessmentId: string, userId: string) => {
    try {
      const assessment = await prisma.riskAssessment.findFirst({
        where: {
          id: assessmentId,
          userId: userId,
        },
      });

      if (!assessment) {
        throw new Error('Assessment not found');
      }

      // Generate PDF filename
      const filename = `risk-report-${assessmentId}-${Date.now()}.pdf`;
      const filepath = path.join(process.cwd(), 'reports', filename);

      // Ensure reports directory exists
      const reportsDir = path.join(process.cwd(), 'reports');
      if (!fs.existsSync(reportsDir)) {
        fs.mkdirSync(reportsDir, { recursive: true });
      }

      // Create simple text-based report (in production, use jsPDF or similar)
      const reportContent = `
Novocrypt - RISK ASSESSMENT REPORT
========================================

Generated: ${new Date().toISOString()}
Assessment ID: ${assessmentId}

ASSESSMENT DETAILS
------------------
Industry: ${assessment.industry}
Data Type: ${assessment.dataType}
Encryption: ${assessment.encryption}
Data Lifetime: ${assessment.dataLifetime} years

RISK SCORE
----------
Score: ${assessment.riskScore}/100
Level: ${assessment.riskLevel}
Years Until Risk: ${Math.max(0, 2035 - new Date().getFullYear())}

RECOMMENDATIONS
---------------
${assessment.recommendations}

NEXT STEPS
----------
1. Review your encryption strategy
2. Plan migration to post-quantum algorithms
3. Implement quantum-safe protocols
4. Test compatibility with existing systems
5. Train your team on quantum threats

---
This report was generated by Novocrypt
For more information, visit novocrypt.com
`;

      // Write report to file
      fs.writeFileSync(filepath, reportContent, 'utf-8');

      // Return file URL (relative to public folder)
      return {
        filename,
        fileUrl: `/reports/${filename}`,
        filepath,
      };
    } catch (error) {
      throw new Error(`Failed to generate PDF report: ${error}`);
    }
  },

  generateHtmlReport: async (assessmentId: string, userId: string) => {
    try {
      const assessment = await prisma.riskAssessment.findFirst({
        where: {
          id: assessmentId,
          userId: userId,
        },
      });

      if (!assessment) {
        throw new Error('Assessment not found');
      }

      const htmlContent = `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Novocrypt - Risk Assessment Report</title>
  <style>
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      line-height: 1.6;
      color: #333;
      max-width: 900px;
      margin: 0 auto;
      padding: 40px;
      background: #f5f5f5;
    }
    .container {
      background: white;
      padding: 40px;
      border-radius: 8px;
      box-shadow: 0 2px 8px rgba(0,0,0,0.1);
    }
    h1 { color: #1e40af; border-bottom: 3px solid #1e40af; padding-bottom: 10px; }
    h2 { color: #1e40af; margin-top: 30px; }
    .risk-score {
      font-size: 48px;
      font-weight: bold;
      color: #1e40af;
      margin: 20px 0;
    }
    .risk-level {
      display: inline-block;
      padding: 8px 16px;
      border-radius: 4px;
      font-weight: bold;
      color: white;
      margin-bottom: 20px;
    }
    .risk-level.low { background: #10b981; }
    .risk-level.medium { background: #f59e0b; }
    .risk-level.high { background: #ef4444; }
    .risk-level.critical { background: #991b1b; }
    .details {
      background: #f9fafb;
      padding: 20px;
      border-radius: 4px;
      margin: 20px 0;
    }
    .detail-row {
      display: flex;
      justify-content: space-between;
      padding: 10px 0;
      border-bottom: 1px solid #e5e7eb;
    }
    .detail-row:last-child {
      border-bottom: none;
    }
    .recommendations {
      background: #eff6ff;
      padding: 20px;
      border-left: 4px solid #1e40af;
      border-radius: 4px;
      margin: 20px 0;
    }
    .footer {
      margin-top: 40px;
      padding-top: 20px;
      border-top: 1px solid #e5e7eb;
      text-align: center;
      color: #666;
      font-size: 12px;
    }
  </style>
</head>
<body>
  <div class="container">
    <h1>Novocrypt - Risk Assessment Report</h1>
    <p><em>Generated: ${new Date().toLocaleDateString()}</em></p>

    <h2>Assessment Summary</h2>
    <div class="risk-score">${assessment.riskScore}</div>
    <div class="risk-level ${assessment.riskLevel.toLowerCase()}">${assessment.riskLevel}</div>
    <p><strong>Years Until Risk:</strong> ${Math.max(0, 2035 - new Date().getFullYear())} years (Q-Day: 2035)</p>

    <h2>Assessment Details</h2>
    <div class="details">
      <div class="detail-row">
        <span><strong>Industry:</strong></span>
        <span>${assessment.industry}</span>
      </div>
      <div class="detail-row">
        <span><strong>Data Type:</strong></span>
        <span>${assessment.dataType}</span>
      </div>
      <div class="detail-row">
        <span><strong>Current Encryption:</strong></span>
        <span>${assessment.encryption}</span>
      </div>
      <div class="detail-row">
        <span><strong>Data Lifetime:</strong></span>
        <span>${assessment.dataLifetime} years</span>
      </div>
    </div>

    <h2>Recommendations</h2>
    <div class="recommendations">
      <p>${assessment.recommendations}</p>
    </div>

    <h2>Next Steps</h2>
    <ol>
      <li>Review your current encryption strategy</li>
      <li>Identify systems using vulnerable algorithms</li>
      <li>Plan migration to post-quantum cryptography</li>
      <li>Implement quantum-safe protocols</li>
      <li>Train your team on quantum threats</li>
      <li>Monitor NIST standards and updates</li>
    </ol>

    <div class="footer">
      <p>© 2026 Novocrypt. This report is confidential and for authorized use only.</p>
      <p>For more information, visit novocrypt.com</p>
    </div>
  </div>
</body>
</html>
`;

      const filename = `risk-report-${assessmentId}-${Date.now()}.html`;
      const filepath = path.join(process.cwd(), 'reports', filename);

      const reportsDir = path.join(process.cwd(), 'reports');
      if (!fs.existsSync(reportsDir)) {
        fs.mkdirSync(reportsDir, { recursive: true });
      }

      fs.writeFileSync(filepath, htmlContent, 'utf-8');

      return {
        filename,
        fileUrl: `/reports/${filename}`,
        filepath,
      };
    } catch (error) {
      throw new Error(`Failed to generate HTML report: ${error}`);
    }
  },

  downloadReport: async (reportId: string, userId: string) => {
    try {
      const report = await prisma.report.findFirst({
        where: {
          id: reportId,
          userId: userId,
        },
      });

      if (!report) {
        throw new Error('Report not found');
      }

      return report;
    } catch (error) {
      throw new Error(`Failed to retrieve report: ${error}`);
    }
  },

  deleteReport: async (reportId: string, userId: string) => {
    try {
      const report = await prisma.report.findFirst({
        where: {
          id: reportId,
          userId: userId,
        },
      });

      if (!report) {
        throw new Error('Report not found');
      }

      // Delete file if exists
      if (report.fileUrl) {
        const filename = report.fileUrl.split('/').pop();
        const filepath = path.join(process.cwd(), 'reports', filename || '');
        if (fs.existsSync(filepath)) {
          fs.unlinkSync(filepath);
        }
      }

      // Delete from database
      await prisma.report.delete({
        where: { id: reportId },
      });

      return { success: true };
    } catch (error) {
      throw new Error(`Failed to delete report: ${error}`);
    }
  },

  /**
   * Orchestrator for sending scheduled reports.
   * Designed to be moved to a BullMQ worker easily in the future.
   */
  processWeeklyReports: async () => {
    const correlationId = `JOB-WEEKLY-${Date.now()}`;
    console.log(`[REPORTING][${correlationId}] Initiating weekly reports...`);
    try {
      // Fetch threats for the last 7 days
      const lastWeek = new Date(Date.now() - 7 * 24 * 60 * 60 * 1000);
      let threats = await prisma.threatItem.findMany({
        where: { publishedAt: { gte: lastWeek } },
        orderBy: { publishedAt: 'desc' },
      });

      // Priority 5: Deterministic severity sorting
      threats.sort((a, b) => {
        const weightA = SEVERITY_WEIGHT[a.severity.toLowerCase()] || 0;
        const weightB = SEVERITY_WEIGHT[b.severity.toLowerCase()] || 0;
        return weightB - weightA;
      });
      threats = threats.slice(0, 100); // Limit report size

      const reportPeriod = getISOWeekString(new Date());

      // Priority 3: Pagination
      const batchSize = parseInt(process.env.REPORT_BATCH_SIZE || '100');
      let cursor: string | undefined = undefined;
      let sentCount = 0;
      let totalUsers = 0;
      let pdfBuffer: Buffer | null = null;

      if (threats.length > 0) {
        pdfBuffer = await reportEngine.generateReportBuffer({
          userId: 'system',
          reportPeriod: 'Weekly Summary',
          startDate: lastWeek,
          endDate: new Date(),
          enabledModules: ['threat_intelligence'],
          cache: new Map()
        });
      }

      while (true) {
        const preferences: any = await (prisma as any).userPreference.findMany({
          where: { weeklySummary: true },
          take: batchSize,
          ...(cursor && { skip: 1, cursor: { id: cursor } }),
          include: { user: true },
        });

        if (preferences.length === 0) break;
        totalUsers += preferences.length;
        cursor = preferences[preferences.length - 1].id;

        for (const pref of preferences) {
          const email = pref.user.email;
          const userId = pref.user.id;
          
          // Priority 2: Isolated try-catch
          try {
            // Priority 7: Idempotency Check (Check if already sent for this period)
            // @ts-ignore
            const alreadySent = await prisma.reportAudit.findUnique({
              where: {
                userId_reportType_reportPeriod: {
                  userId,
                  reportType: 'weekly_summary',
                  reportPeriod,
                },
              },
            });

            if (alreadySent && alreadySent.status === 'sent') {
              console.log(`[REPORTING][${correlationId}] Skipped User ${userId} - Already sent this week.`);
              continue;
            }

            let success = true;
            if (pdfBuffer) {
              success = await withRetry(() => sendEmailReport({
                to: email,
                subject: 'Your Weekly Quantum Threat Summary',
                text: `Here is your weekly summary of quantum cryptography threats. We detected ${threats.length} significant threats.`,
                html: `<p>Hello ${pref.user.name || 'User'},</p><p>Please find attached your Weekly Quantum Threat Summary.</p><p>Stay secure,<br/>NovoCrypt Team</p>`,
                attachments: [
                  {
                    filename: `Weekly-Threat-Report-${new Date().toISOString().split('T')[0]}.pdf`,
                    content: pdfBuffer,
                    contentType: 'application/pdf',
                  },
                ],
              }));
            } else {
               // Send empty report email without PDF
               success = await withRetry(() => sendEmailReport({
                to: email,
                subject: 'Your Weekly Quantum Threat Summary',
                text: `No significant threats detected this week.`,
                html: `<p>Hello ${pref.user.name || 'User'},</p><p>No significant threats were detected in the past 7 days. Your environment remains secure.</p><p>Stay secure,<br/>NovoCrypt Team</p>`,
                attachments: [],
              }));
            }

            await prisma.reportAudit.upsert({
              where: {
                userId_reportType_reportPeriod: {
                  userId,
                  reportType: 'weekly_summary',
                  reportPeriod,
                },
              },
              update: {
                status: success ? 'sent' : 'failed',
                errorLog: success ? null : 'Nodemailer rejection',
                sentAt: new Date(),
              },
              create: {
                userId,
                reportType: 'weekly_summary',
                reportPeriod,
                status: success ? 'sent' : 'failed',
                errorLog: success ? null : 'Nodemailer rejection',
              },
            });

            if (success) {
              sentCount++;
              console.log(`[REPORTING][${correlationId}] Successfully dispatched to ${userId}`);
            } else {
              console.error(`[REPORTING][${correlationId}] Failed dispatch to ${userId}`);
            }
          } catch (userError) {
            console.error(`[REPORTING][${correlationId}] Unhandled error for user ${userId}:`, userError);
            // Log failure but continue processing remaining users
            try {
               await prisma.reportAudit.upsert({
                where: {
                  userId_reportType_reportPeriod: {
                    userId,
                    reportType: 'weekly_summary',
                    reportPeriod,
                  },
                },
                update: {
                  status: 'failed',
                  errorLog: String(userError),
                  sentAt: new Date(),
                },
                create: {
                  userId,
                  reportType: 'weekly_summary',
                  reportPeriod,
                  status: 'failed',
                  errorLog: String(userError),
                },
              });
            } catch (auditError) {
              console.error(`[REPORTING][${correlationId}] Failed to write audit log for ${userId}:`, auditError);
            }
          }
        }
      }

      console.log(`[REPORTING][${correlationId}] Dispatched Weekly Reports to ${sentCount}/${totalUsers} subscribed users.`);
    } catch (error) {
      console.error(`[REPORTING][${correlationId}] Failed to process weekly reports:`, error);
    }
  },

  processMonthlyReports: async () => {
    const correlationId = `JOB-MONTHLY-${Date.now()}`;
    console.log(`[REPORTING][${correlationId}] Initiating monthly reports...`);
    try {
      const lastMonth = new Date(Date.now() - 30 * 24 * 60 * 60 * 1000);
      let threats = await prisma.threatItem.findMany({
        where: { publishedAt: { gte: lastMonth }, category: 'advisory' },
        orderBy: { publishedAt: 'desc' },
      });

      // Priority 5
      threats.sort((a, b) => {
        const weightA = SEVERITY_WEIGHT[a.severity.toLowerCase()] || 0;
        const weightB = SEVERITY_WEIGHT[b.severity.toLowerCase()] || 0;
        return weightB - weightA;
      });
      threats = threats.slice(0, 100);

      const reportPeriod = getMonthString(new Date());

      const batchSize = parseInt(process.env.REPORT_BATCH_SIZE || '100');
      let cursor: string | undefined = undefined;
      let sentCount = 0;
      let totalUsers = 0;
      let pdfBuffer: Buffer | null = null;

      if (threats.length > 0) {
        pdfBuffer = await reportEngine.generateReportBuffer({
          userId: 'system',
          reportPeriod: 'Monthly Compliance',
          startDate: lastMonth,
          endDate: new Date(),
          enabledModules: ['threat_intelligence'],
          cache: new Map()
        });
      }

      while (true) {
        const preferences: any = await (prisma as any).userPreference.findMany({
          where: { monthlyCompliance: true },
          take: batchSize,
          ...(cursor && { skip: 1, cursor: { id: cursor } }),
          include: { user: true },
        });

        if (preferences.length === 0) break;
        totalUsers += preferences.length;
        cursor = preferences[preferences.length - 1].id;

        for (const pref of preferences) {
          const email = pref.user.email;
          const userId = pref.user.id;
          
          try {
            const alreadySent = await prisma.reportAudit.findUnique({
              where: {
                userId_reportType_reportPeriod: {
                  userId,
                  reportType: 'monthly_compliance',
                  reportPeriod,
                },
              },
            });

            if (alreadySent && alreadySent.status === 'sent') {
               console.log(`[REPORTING][${correlationId}] Skipped User ${userId} - Already sent this month.`);
               continue;
            }

            let success = true;
            if (pdfBuffer) {
              success = await withRetry(() => sendEmailReport({
                to: email,
                subject: 'Monthly Compliance & Quantum Readiness Report',
                text: 'Please find attached your Monthly Compliance Report.',
                html: `<p>Hello ${pref.user.name || 'User'},</p><p>Please find attached your Monthly Compliance Report.</p><p>Stay secure,<br/>NovoCrypt Team</p>`,
                attachments: [
                  {
                    filename: `Monthly-Compliance-Report-${new Date().toISOString().split('T')[0]}.pdf`,
                    content: pdfBuffer,
                    contentType: 'application/pdf',
                  },
                ],
              }));
            } else {
               success = await withRetry(() => sendEmailReport({
                to: email,
                subject: 'Monthly Compliance & Quantum Readiness Report',
                text: 'No compliance updates this month.',
                html: `<p>Hello ${pref.user.name || 'User'},</p><p>There are no new compliance advisories this month.</p><p>Stay secure,<br/>NovoCrypt Team</p>`,
                attachments: [],
              }));
            }

            await prisma.reportAudit.upsert({
              where: {
                userId_reportType_reportPeriod: {
                  userId,
                  reportType: 'monthly_compliance',
                  reportPeriod,
                },
              },
              update: {
                status: success ? 'sent' : 'failed',
                errorLog: success ? null : 'Nodemailer rejection',
                sentAt: new Date(),
              },
              create: {
                userId,
                reportType: 'monthly_compliance',
                reportPeriod,
                status: success ? 'sent' : 'failed',
                errorLog: success ? null : 'Nodemailer rejection',
              },
            });

            if (success) {
              sentCount++;
              console.log(`[REPORTING][${correlationId}] Successfully dispatched to ${userId}`);
            } else {
              console.error(`[REPORTING][${correlationId}] Failed dispatch to ${userId}`);
            }
          } catch (userError) {
            console.error(`[REPORTING][${correlationId}] Unhandled error for user ${userId}:`, userError);
            try {
               await prisma.reportAudit.upsert({
                where: {
                  userId_reportType_reportPeriod: {
                    userId,
                    reportType: 'monthly_compliance',
                    reportPeriod,
                  },
                },
                update: {
                  status: 'failed',
                  errorLog: String(userError),
                  sentAt: new Date(),
                },
                create: {
                  userId,
                  reportType: 'monthly_compliance',
                  reportPeriod,
                  status: 'failed',
                  errorLog: String(userError),
                },
              });
            } catch (auditError) {}
          }
        }
      }

      console.log(`[REPORTING][${correlationId}] Dispatched Monthly Reports to ${sentCount}/${totalUsers} subscribed users.`);
    } catch (error) {
      console.error(`[REPORTING][${correlationId}] Failed to process monthly reports:`, error);
    }
  },
};
