import { prisma } from '../config/database';
import * as fs from 'fs';
import * as path from 'path';

export const reportService = {
  generatePdfReport: async (assessmentId: string, userId: string) => {
    try {
      const assessment = await prisma.riskAssessment.findFirst({
        where: {
          id: assessmentId,
          userId: userId,
        },
      });

      if (!assessment) {
        throw new Error('Assessment not found');
      }

      // Generate PDF filename
      const filename = `risk-report-${assessmentId}-${Date.now()}.pdf`;
      const filepath = path.join(process.cwd(), 'reports', filename);

      // Ensure reports directory exists
      const reportsDir = path.join(process.cwd(), 'reports');
      if (!fs.existsSync(reportsDir)) {
        fs.mkdirSync(reportsDir, { recursive: true });
      }

      // Create simple text-based report (in production, use jsPDF or similar)
      const reportContent = `
Novocrypt - RISK ASSESSMENT REPORT
========================================

Generated: ${new Date().toISOString()}
Assessment ID: ${assessmentId}

ASSESSMENT DETAILS
------------------
Industry: ${assessment.industry}
Data Type: ${assessment.dataType}
Encryption: ${assessment.encryption}
Data Lifetime: ${assessment.dataLifetime} years

RISK SCORE
----------
Score: ${assessment.riskScore}/100
Level: ${assessment.riskLevel}
Years Until Risk: ${assessment.yearsUntilRisk}

RECOMMENDATIONS
---------------
${assessment.recommendations}

NEXT STEPS
----------
1. Review your encryption strategy
2. Plan migration to post-quantum algorithms
3. Implement quantum-safe protocols
4. Test compatibility with existing systems
5. Train your team on quantum threats

---
This report was generated by Novocrypt
For more information, visit novocrypt.com
`;

      // Write report to file
      fs.writeFileSync(filepath, reportContent, 'utf-8');

      // Return file URL (relative to public folder)
      return {
        filename,
        fileUrl: `/reports/${filename}`,
        filepath,
      };
    } catch (error) {
      throw new Error(`Failed to generate PDF report: ${error}`);
    }
  },

  generateHtmlReport: async (assessmentId: string, userId: string) => {
    try {
      const assessment = await prisma.riskAssessment.findFirst({
        where: {
          id: assessmentId,
          userId: userId,
        },
      });

      if (!assessment) {
        throw new Error('Assessment not found');
      }

      const htmlContent = `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Novocrypt - Risk Assessment Report</title>
  <style>
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      line-height: 1.6;
      color: #333;
      max-width: 900px;
      margin: 0 auto;
      padding: 40px;
      background: #f5f5f5;
    }
    .container {
      background: white;
      padding: 40px;
      border-radius: 8px;
      box-shadow: 0 2px 8px rgba(0,0,0,0.1);
    }
    h1 { color: #1e40af; border-bottom: 3px solid #1e40af; padding-bottom: 10px; }
    h2 { color: #1e40af; margin-top: 30px; }
    .risk-score {
      font-size: 48px;
      font-weight: bold;
      color: #1e40af;
      margin: 20px 0;
    }
    .risk-level {
      display: inline-block;
      padding: 8px 16px;
      border-radius: 4px;
      font-weight: bold;
      color: white;
      margin-bottom: 20px;
    }
    .risk-level.low { background: #10b981; }
    .risk-level.medium { background: #f59e0b; }
    .risk-level.high { background: #ef4444; }
    .risk-level.critical { background: #991b1b; }
    .details {
      background: #f9fafb;
      padding: 20px;
      border-radius: 4px;
      margin: 20px 0;
    }
    .detail-row {
      display: flex;
      justify-content: space-between;
      padding: 10px 0;
      border-bottom: 1px solid #e5e7eb;
    }
    .detail-row:last-child {
      border-bottom: none;
    }
    .recommendations {
      background: #eff6ff;
      padding: 20px;
      border-left: 4px solid #1e40af;
      border-radius: 4px;
      margin: 20px 0;
    }
    .footer {
      margin-top: 40px;
      padding-top: 20px;
      border-top: 1px solid #e5e7eb;
      text-align: center;
      color: #666;
      font-size: 12px;
    }
  </style>
</head>
<body>
  <div class="container">
    <h1>Novocrypt - Risk Assessment Report</h1>
    <p><em>Generated: ${new Date().toLocaleDateString()}</em></p>

    <h2>Assessment Summary</h2>
    <div class="risk-score">${assessment.riskScore}</div>
    <div class="risk-level ${assessment.riskLevel.toLowerCase()}">${assessment.riskLevel}</div>
    <p><strong>Years Until Risk:</strong> ${assessment.yearsUntilRisk} years (Q-Day: 2035)</p>

    <h2>Assessment Details</h2>
    <div class="details">
      <div class="detail-row">
        <span><strong>Industry:</strong></span>
        <span>${assessment.industry}</span>
      </div>
      <div class="detail-row">
        <span><strong>Data Type:</strong></span>
        <span>${assessment.dataType}</span>
      </div>
      <div class="detail-row">
        <span><strong>Current Encryption:</strong></span>
        <span>${assessment.encryption}</span>
      </div>
      <div class="detail-row">
        <span><strong>Data Lifetime:</strong></span>
        <span>${assessment.dataLifetime} years</span>
      </div>
    </div>

    <h2>Recommendations</h2>
    <div class="recommendations">
      <p>${assessment.recommendations}</p>
    </div>

    <h2>Next Steps</h2>
    <ol>
      <li>Review your current encryption strategy</li>
      <li>Identify systems using vulnerable algorithms</li>
      <li>Plan migration to post-quantum cryptography</li>
      <li>Implement quantum-safe protocols</li>
      <li>Train your team on quantum threats</li>
      <li>Monitor NIST standards and updates</li>
    </ol>

    <div class="footer">
      <p>© 2026 Novocrypt. This report is confidential and for authorized use only.</p>
      <p>For more information, visit novocrypt.com</p>
    </div>
  </div>
</body>
</html>
`;

      const filename = `risk-report-${assessmentId}-${Date.now()}.html`;
      const filepath = path.join(process.cwd(), 'reports', filename);

      const reportsDir = path.join(process.cwd(), 'reports');
      if (!fs.existsSync(reportsDir)) {
        fs.mkdirSync(reportsDir, { recursive: true });
      }

      fs.writeFileSync(filepath, htmlContent, 'utf-8');

      return {
        filename,
        fileUrl: `/reports/${filename}`,
        filepath,
      };
    } catch (error) {
      throw new Error(`Failed to generate HTML report: ${error}`);
    }
  },

  downloadReport: async (reportId: string, userId: string) => {
    try {
      const report = await prisma.report.findFirst({
        where: {
          id: reportId,
          userId: userId,
        },
      });

      if (!report) {
        throw new Error('Report not found');
      }

      return report;
    } catch (error) {
      throw new Error(`Failed to retrieve report: ${error}`);
    }
  },

  deleteReport: async (reportId: string, userId: string) => {
    try {
      const report = await prisma.report.findFirst({
        where: {
          id: reportId,
          userId: userId,
        },
      });

      if (!report) {
        throw new Error('Report not found');
      }

      // Delete file if exists
      if (report.fileUrl) {
        const filename = report.fileUrl.split('/').pop();
        const filepath = path.join(process.cwd(), 'reports', filename || '');
        if (fs.existsSync(filepath)) {
          fs.unlinkSync(filepath);
        }
      }

      // Delete from database
      await prisma.report.delete({
        where: { id: reportId },
      });

      return { success: true };
    } catch (error) {
      throw new Error(`Failed to delete report: ${error}`);
    }
  },
};
