export const ALGORITHMS_DATA = [
  {
    name: 'RSA-2048',
    category: 'Classical',
    keySize: 2048,
    timeComplexity: 'O(log³ n)',
    quantumSafe: false,
    nistApproved: true,
    status: 'Vulnerable to Q-Day',
  },
  {
    name: 'RSA-4096',
    category: 'Classical',
    keySize: 4096,
    timeComplexity: 'O(log³ n)',
    quantumSafe: false,
    nistApproved: true,
    status: 'Vulnerable to Q-Day',
  },
  {
    name: 'ECC-256',
    category: 'Classical',
    keySize: 256,
    timeComplexity: 'O(log n)',
    quantumSafe: false,
    nistApproved: true,
    status: 'Vulnerable to Q-Day',
  },
  {
    name: 'CRYSTALS-Kyber',
    category: 'Post-Quantum',
    keySize: 3072,
    timeComplexity: 'O(log n)',
    quantumSafe: true,
    nistApproved: true,
    status: 'NIST Approved 2022',
  },
  {
    name: 'CRYSTALS-Dilithium',
    category: 'Post-Quantum',
    keySize: 2560,
    timeComplexity: 'O(log n)',
    quantumSafe: true,
    nistApproved: true,
    status: 'NIST Approved 2022',
  },
  {
    name: 'FALCON',
    category: 'Post-Quantum',
    keySize: 897,
    timeComplexity: 'O(log n)',
    quantumSafe: true,
    nistApproved: true,
    status: 'NIST Approved 2022',
  },
  {
    name: 'SPHINCS+',
    category: 'Post-Quantum',
    keySize: 64,
    timeComplexity: 'O(n)',
    quantumSafe: true,
    nistApproved: true,
    status: 'NIST Approved 2022',
  },
];

export const NIST_STANDARDS = [
  {
    year: 2022,
    algorithm: 'CRYSTALS-Kyber (ML-KEM)',
    type: 'Key Encapsulation',
    description: 'Lattice-based key establishment',
  },
  {
    year: 2022,
    algorithm: 'CRYSTALS-Dilithium (ML-DSA)',
    type: 'Digital Signature',
    description: 'Lattice-based digital signature',
  },
  {
    year: 2022,
    algorithm: 'FALCON (SLH-DSA)',
    type: 'Digital Signature',
    description: 'Lattice-based digital signature',
  },
  {
    year: 2023,
    algorithm: 'SPHINCS+',
    type: 'Digital Signature',
    description: 'Hash-based digital signature',
  },
];
