import PDFDocument from 'pdfkit';
import { ReportSection, ReportContext } from './ReportSection';

export class ReportEngine {
  private sections: Map<string, ReportSection> = new Map();

  registerSection(section: ReportSection) {
    if (this.sections.has(section.id)) {
      throw new Error(`ReportEngine: A section with ID '${section.id}' is already registered.`);
    }
    this.sections.set(section.id, section);
  }

  async generateReportBuffer(context: ReportContext): Promise<Buffer> {
    return new Promise(async (resolve, reject) => {
      try {
        const doc = new PDFDocument({ margin: 50, size: 'A4', bufferPages: true });
        const chunks: Buffer[] = [];

        doc.on('data', (chunk) => chunks.push(chunk));
        doc.on('end', () => resolve(Buffer.concat(chunks)));
        doc.on('error', (err) => reject(err));

        this.renderHeader(doc, context);

        // Filter enabled and sort by order
        const activeSections = Array.from(this.sections.values())
          .filter(s => context.enabledModules.includes(s.id))
          .sort((a, b) => a.order - b.order);

        let dataFound = false;

        for (const section of activeSections) {
          try {
            // 1. Check Authorization
            if (section.isAuthorized) {
              const authorized = await section.isAuthorized(context);
              if (!authorized) {
                console.log(`ReportEngine: Skipping section '${section.id}' - Unauthorized.`);
                continue;
              }
            }

            // 2. Fetch Data
            const hasData = await section.fetchData(context);
            if (hasData) {
              dataFound = true;
              
              // Draw Section Separator
              doc.moveDown(3);
              doc.rect(50, doc.y, doc.page.width - 100, 1).fill('#e2e8f0');
              doc.moveDown(1);
              
              doc.fontSize(20).fillColor('#1e293b').text(section.title);
              doc.moveDown(1);
              
              // 3. Render Section
              await section.renderPdf(doc, context);
            }
          } catch (sectionError) {
            console.error(`ReportEngine: Failed to generate section '${section.id}':`, sectionError);
            
            // Render failure banner instead of crashing the whole report
            doc.moveDown(3);
            doc.rect(50, doc.y, doc.page.width - 100, 1).fill('#fecaca');
            doc.moveDown(1);
            doc.fontSize(20).fillColor('#1e293b').text(section.title);
            doc.moveDown(0.5);
            doc.fontSize(10).fillColor('#ef4444').text(`Failed to generate ${section.title} section. Please contact support if this issue persists.`, { align: 'justify' });
            dataFound = true; // Prevents "No data" message
          }
        }

        if (!dataFound) {
          doc.moveDown(2);
          doc.fontSize(12).fillColor('#64748b').text('No data available for the selected modules in this reporting period.', { align: 'center' });
        }

        this.renderFooter(doc);
        doc.end();
      } catch (error) {
        reject(error);
      }
    });
  }

  private renderHeader(doc: PDFKit.PDFDocument, context: ReportContext) {
    doc.rect(0, 0, doc.page.width, 10).fill('#0ea5e9'); // Top accent bar
    doc.moveDown(3);
    
    doc.fontSize(28).fillColor('#0f172a').text('NovoCrypt Executive Security Report', { align: 'center' });
    doc.moveDown(1);
    doc.fontSize(12).fillColor('#64748b')
      .text(`Generated: ${new Date().toLocaleString()}`, { align: 'center' })
      .moveDown(0.2);
      
    if (context.organizationName) {
      doc.text(`Organization: ${context.organizationName}`, { align: 'center' }).moveDown(0.2);
    }
    doc.text(`Report Period: ${context.reportPeriod}`, { align: 'center' });
    doc.moveDown(4);
    
    // Executive Summary
    doc.fontSize(16).fillColor('#1e293b').text('Executive Summary');
    doc.moveDown(0.5);
    doc.fontSize(11).fillColor('#475569').text(
      'This report provides an aggregated executive view of your organization\'s quantum risk posture, threat intelligence, and compliance status. The findings within are dynamically generated from active NovoCrypt modules.', 
      { align: 'justify', lineGap: 2 }
    );
  }

  private renderFooter(doc: PDFKit.PDFDocument) {
    const pages = doc.bufferedPageRange().count;
    for (let i = 0; i < pages; i++) {
      doc.switchToPage(i);
      
      // Footer text
      doc.fontSize(9).fillColor('#94a3b8').text(
        'Generated by NovoCrypt Executive Reporting Engine',
        50,
        doc.page.height - 40,
        { align: 'left', lineBreak: false }
      );
      
      // Page numbers
      doc.fontSize(9).fillColor('#94a3b8').text(
        `Page ${i + 1} of ${pages}`,
        doc.page.width - 100,
        doc.page.height - 40,
        { align: 'right', lineBreak: false }
      );
    }
  }
}

export const reportEngine = new ReportEngine();
